# Указываем путь к исходникам BOINC
BOINC_ROOT = /home/boinc

CXX = g++
# Добавляем include-путь BOINC
CXXFLAGS = -O2 -std=c++17 -I$(BOINC_ROOT)/include
# Добавляем библиотечный путь BOINC и линковку с boinc_api
LDFLAGS = -L$(BOINC_ROOT)/lib -lboinc_api
TARGET = latin_compute

all: $(TARGET)

$(TARGET): compute_app.cpp
	$(CXX) $(CXXFLAGS) compute_app.cpp -o $(TARGET) $(LDFLAGS)

clean:
	rm -f $(TARGET)